os: linux
sudo: false
language: python
cache: 
  - pip
  - pip3

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

install: 
  - pip3 install -r requirements.txt
  - pip3 install pytest-cov
  - pip3 install coveralls

script: pytest --cov flask_zipper test.py

notifications:
  email: false
